### ISSUE TITLE
Request for the files and code for recreating Figure 5

### ISSUE THREAD

**Issue by cshoben** [IttaiEres/HiCiPSC#2]
Hello, 

I see that any figures using pyGenomeTracks are not included in this Github space (please correct me if I missed this). Is this available somewhere else? 

1) I'm specifically interested in recreating Figure 5. Any notes on which R code/scripts created output files that then served as the input for the pyGenomeTracks scripts would be extremely helpful. Based on the pyGenomeTracks documentation, I am looking for the .h5 file which serves as the [hic matrix] and the .bed file which serves as the [tads] in the pyGenomeTracks configuration file. I'm referring to information located here:
https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-hi-c-data
It would be great to be able to download these files and to see the code used in creating them.

2) Juicer_Mega Analyses at this link https://ittaieres.github.io/HiCiPSC/TADs.html#juicer_mega_analyses
is where I see the .hic files talked about, however the link just takes me to an email conversation which is very difficult to comb through to figure out how the .hic files were made. I am under the impression that this .hic file was somehow turned into a .h5 file for use with pyGenomeTracks? 

3) My impression is that the TADs are from the Arrowhead analysis (based on description in Figure 5 legend) examining the individual-level data but I'd like to check with you as many TAD analyses were executed and I'm not fully confident which analysis is appropriate (I'm looking at this webpage: https://ittaieres.github.io/HiCiPSC/TADs.html#introduction). I also see:
https://github.com/IttaiEres/HiCiPSC/tree/master/data/TADs/scripts 
but do not see where the TAD.bed files are or anything that seems to have produced these .bed files. 

Thank you for your help!

Sincerely,
Chelsea

**Comment by cshoben** [comment]
Hello again, 

After a bit more familiarity with pyGenomeTracks, I understand that one of the files I will want to see is the "configuration file" for pyGenomeTracks, which will be a .ini file type. I realize that there are many options within this file that were likely tweaked/set in order to create Figure 5 from the paper. So only having the .h5 and the .bed files will not quite allow me to understand the .ini file that was fed into the script used with the "pyGenomeTracks" command. This is the file that is referenced after the "--tracks" flag. Thank you again for sharing this and your time.

**Comment by IttaiEres** [comment]
Hi Chelsea,

Apologies for my delayed response--I assume this is not relevant anymore but I am going to strive to provide answers where I can regardless. I note that I currently do not (and sadly did not even at the time of your message) still have access to many of the scripts that you desire as examples nor the input files for them, both because of leaving my previous institution, and due to a hard drive death. Sorry for that.

You are correct that those figures were not available in this repository. The code to create them was not available elsewhere either. From what I recall, using pyGenomeTracks was quite the hassle on my university's compute environment, so not sure how much use those individual scripts may have been anyways. Regardless, to address your individual inquiries:
1. Sorry I'm not able to provide these or the .ini file you later reference.
2. [Here ](https://github.com/aidenlab/juicer/blob/main/AWS/scripts/mega.sh)is the script that is used for combining .hic files. If I am remembering correctly, I used [HicExplorer](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html) to convert the .hic to h5.
3. You are correct, those are from Arrowhead.

Thanks,
Ittai
